name: Python Release - Conda

on: push

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}

jobs:
  build_and_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.5, 3.6, 3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          channels: "defaults,conda-forge"
          conda-build-version: "3.20.5"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Extract version
        working-directory: ./bindings/python
        run: |
          conda install -c conda-forge setuptools-rust
          echo "TOKENIZERS_VERSION=`python setup.py --version`" >> $GITHUB_ENV

      - name: Build conda packages
        run: conda build .github/conda

      - name: Upload to Anaconda

        run: |
          conda install anaconda-client
          anaconda upload `conda build .github/conda --output`
